[package]
name = "rustycard"
version = "0.1.0"
edition = "2021"

[dependencies]
dioxus = { version = "0.2", features = ["desktop", "router"] }
rusqlite = { version = "0.27", features = ["bundled"] }
pulldown-cmark = "0.9"
